[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
apus_depin = "12EsXujv2DgAgMBKzBJSS92tvMWQefg8C8kpfSP11o1E"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/zhoujianing/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
